server:
  port: 8084
sa:
  version: @project.version@
  jwt:
    header: X-Token
    secret: 4f1aaeeb0a76ac6033c5e61d8b5e3e6f
    expire: 604800
  swagger2:
    enabled: true
spring:
  messages:
    encoding: UTF-8
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    #url: jdbc:h2:file:./data/demo
    url: jdbc:h2:file:./data/mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    initialization-mode: always
    #schema: classpath:db/schema-h2.sql
  h2:
    console:
      path: /h2-console  #h2嵌入式数据库控制台，可以通过浏览器访问
      enabled: true
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
logging:
  level:
    root:  info
    org.springframework:  info
    org.hibernate.type.descriptor.sql.BasicBinder: info